### ISSUE TITLE
Set Data

### ISSUE THREAD

**Issue by grohong** [Data-Competition/Super-Mario#1]
## Data - Mush room data
 Data sets of edible and poisonous mushrooms

- [x] The components are summarized
![2018-07-18 3 41 36](https://user-images.githubusercontent.com/31721963/42864693-48168d66-8aa2-11e8-8101-4685adb00b0b.png)

- [x] Summary of results
![2018-07-18 3 41 43](https://user-images.githubusercontent.com/31721963/42864768-82f5d0c2-8aa2-11e8-8615-b50d2ed6a91a.png)

**Comment by kozistr** [comment]
Maybe, this one is already done!
